version: '3'
services:
  db:
    image: postgres:9.6.1-alpine
    ports:
        - "5432:5432"
    environment:
      POSTGRES_DB: rails
      POSTGRES_USER: rails
      POSTGRES_PASSWORD: rails
  rails:
    image: rails
    command: tail -f /dev/null
    links:
      - db
    volumes:
      - .:/app
    ports:
      - "3000:3000"
